trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'AVVAcon'
  IMAGE_NAME: 'avva-app'

steps:
- task: DockerInstaller@0
  displayName: Install Docker (if missing)

- task: Docker@2
  displayName: Build and push app image to ACR
  inputs:
    containerRegistry: 'Thejas_connect'     # <- your service connection name
    repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: 'app/Dockerfile'
    buildContext: 'app'
    tags: |
      $(Build.BuildId)
