trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  displayName: Install Docker

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'AVVAcon_docker'   # <-- your docker registry service connection
    repository: 'avva-app'
    command: 'buildAndPush'
    Dockerfile: 'app/Dockerfile'
    buildContext: 'app'
    tags: |
      $(Build.BuildId)
